# docker-compose.yml
version: '1'

services:
    
  db:
    container_name: moneybackward-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./ignore/_postgres-data:/var/lib/postgresql/data

  be-lint:
    container_name: moneybackward-be-lint
    image: golangci/golangci-lint:v1.55-alpine
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: golangci-lint run -v

  be:
    container_name: moneybackward-be
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/app
    restart: always
    build: 
      dockerfile: ./dockerfiles/be.Dockerfile
    command: go run main.go
