name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: golangci

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with: 
        go-version: 1.13         

    - name: Build app 
      run: go build -o moneybackward-be main.go

    - name: SCP to Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: 
        source: "app"         
        target: "dist"    

    - name: Deploy and rebuild on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.PORT }}
        script:           
          systemctl restart goweb.service &&
          systemctl status goweb       
