name: deploy

on:
  workflow_run:
    workflows: ["golangci-lint"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Go 1.21
      uses: actions/setup-go@v1
      with: 
        go-version: 1.21
    
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        cat .env

    - name: Build app 
      run: go build -o moneybackward-be main.go

    - name: SCP to Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: 
        source: "moneybackward-be"         
        target: "/home/moneybackward/bin/"    

    - name: Deploy and rebuild on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_KEY }}
        port:
        script:           
          systemctl --user restart ${{ secrets.SERVICE_NAME }}.service &&
          systemctl --user status ${{ secrets.SERVICE_NAME }}
